name: CI

on:
  pull_request:
    type: [opened, synchronize, reopened]

jobs:
  check-branch-name:
    name: check the branch name
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^(feature|bugfix|improvement|library)\/[a-z0-9_.-]+\/?([0-9]+)?$'
          allowed_prefixes: 'feature,bugfix,improvement,library'
          ignore: main,dev
          min_length: 5
          max_length: 50

  sonarcloud:
    name: sonarcloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: sonarcloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
